namespace MicrosoftDocsGallery
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        void openHomePage();
        void openFundamentalsPage();
        void openSettingsPage();
        void openWebViewPage(String url);
        Windows.Foundation.IAsyncAction SetIconAsync(Microsoft.UI.Windowing.AppWindow window);
        void InitWindowStyle(Microsoft.UI.Xaml.Window window);

    }
}
